name: dotnet package
 
on:
  workflow_dispatch
 
jobs:
  build:
 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '3.1.x', '6.0.x' ]
 
    steps:
      - uses: actions/checkout@v5
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v5
        id: stepid
        with:
          dotnet: ${{ matrix.dotnet-version }}
      - name: Create temporary global.json
        run: echo '{"sdk":{"version":"${{ steps.stepid.outputs.dotnet-version }}"}}' > ./global.json
      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version
